### PR TITLE
Add option to call tarsnap with a function

### PR DESCRIPTION
**Pull request by wraugh**

### CODE REVIEW

**Comment by assistcontrol** [comment]
This is a great idea!

**Comment by assistcontrol** [comment]
`calltarsnap()` feels a little obtuse to me. I feel like simply `tarsnap()` might be more fluent. Do you agree?

**Comment by wraugh** [comment]
The tarsnap command itself, if it's in $PATH, already uses the name `tarsnap`. I don't feel comfortable overriding that.

**Comment by alexjurkiewicz** [comment]
Should this deprecate the dedicated pre/post script logic? It _could_ but I'm not sure if it's a good idea. Thoughts?

**Comment by wraugh** [comment]
I think stability is more important than a tight design (especially in a fire-and-forget system like `acts`) so I would not deprecate anything.

**Comment by assistcontrol** [comment]
> The tarsnap command itself, if it's in $PATH, already uses the name `tarsnap`. I don't feel comfortable overriding that.

Ah, of course. That is completely correct.

I am on vacation right now, but I’ll merge this when I get back.

**Pull request merged**
